# conf/config.yaml

masking:
  sigma: 3
  min_blob_size: 3
  blocking_radius: 1.5
  blocking_percentile: 95
  exclude_solvent: true
  dark_size_threshold: 0.1
  exclude_positive_diffmap: true
  exclude_large_occupancy_outliers: false

map_processing:
  diffmap_type: "tv"
  dark_mean_correction: true
  diffmap_mean_correction: true
  diffmap_v2_correction: false
  preprocessing: false

plot:
  show_ignored_voxels: true
  set_ylim: false
  is_composite: false
  std_cutoff: 3.0
  solvent_density: 0.4
  minimum_datapoints: 10

general:
  name_machine: "unnamed_experiment"
  name_human: ${oc.select:general.name_human,${general.name_machine}}
  output_base_folder: "tmp"
  output_folder: "${general.output_base_folder}/${general.name_machine}/"
  map_sampling: 3
  high_resolution_limit: 0.1
  pdbloc_dark: "${input_files.pdb_dark}"
  comparison_type: "triggered"

input_files:
  data_folder: null
  map_dark: ???       # '???' means this value is MANDATORY and must be provided
  map_triggered: none       # '???' means this value is MANDATORY and must be provided
  map_diff: none       # '???' means this value is MANDATORY and must be provided
  pdb_dark: ???
  pdb_triggered: null
  columns_dark: 
    amplitude_column: ???
    phase_column: ???
    uncertainty_column: ???
  columns_triggered:
    amplitude_column: null
    phase_column: null
    uncertainty_column: null
  columns_diff:
    amplitude_column: null
    phase_column: null
    uncertainty_column: null
  impose_dark_phases: true
  columns_are_ints: false